import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Static Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Deploying Static NextJS Apps
        </h1>

        <p className={styles.description}>
          Get started by going to{' '}
          <code className={styles.code}>README.md</code>
          and follow the steps.
        </p>

        <div className={styles.grid}>
          <a href="https://vent.io" className={styles.card}>
            <h2>Website &rarr;</h2>
            <p>Interested in working with us? Take a look at our webpage</p>
          </a>

          <a href="https://github.com/Slakkan/next-static" className={styles.card}>
            <h2>Repository &rarr;</h2>
            <p>Clone this repo and read the README.md to get started.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vent.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Presented by{' '}
          <span className={styles.logo}>
            <Image src="/images/jpg/ventio-logo.jpg" alt="ventio-logo" width={124} height={76} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
